export type PolicyCategory = "Baseline" | "AgentShield Signature" | "Custom Library";
export type PolicyDecision = "Allow" | "Challenge" | "Deny" | "Monitor" | "Quarantine";
export type PolicyEnforcementMode = "Monitor" | "Challenge" | "Block" | "Quarantine";

export type PolicyTemplate = {
  id: string;
  name: string;
  category: PolicyCategory;
  pack: string;
  decision: PolicyDecision;
  enforcementMode: PolicyEnforcementMode;
  riskTier: "Low" | "Medium" | "High" | "Critical";
  rule: string;
  businessValue: string;
  configuration: string[];
  evidence: string[];
  frameworks: string[];
};

export type TenantPolicy = PolicyTemplate & {
  tenantId: string;
  status: "Available" | "Active" | "Draft";
  source: "standard" | "cloned";
  createdAt: string;
  updatedAt: string;
};

export const requiredBaselinePolicies: PolicyTemplate[] = [
  {
    id: "agent-registration-required",
    name: "Agent Registration Required",
    category: "Baseline",
    pack: "Required Baseline",
    decision: "Deny",
    enforcementMode: "Block",
    riskTier: "High",
    rule: "Block or flag agents, bots, service principals, and workflow identities that are not registered before production use.",
    businessValue: "Creates the authoritative inventory customers need before they can govern agent risk.",
    configuration: ["Required environments", "Approved agent sources", "Exception approver"],
    evidence: ["Agent registry record", "Discovery source", "Approval decision"],
    frameworks: ["NIST CSF", "ISO 27001", "SOC 2", "CIS"],
  },
  {
    id: "human-owner-sponsor-required",
    name: "Human Owner And Sponsor Required",
    category: "Baseline",
    pack: "Required Baseline",
    decision: "Challenge",
    enforcementMode: "Challenge",
    riskTier: "High",
    rule: "Require a business owner, technical owner, and backup sponsor for every agent and non-human identity.",
    businessValue: "Prevents ownerless automation from becoming unmanaged risk.",
    configuration: ["Owner role", "Sponsor role", "Review cadence"],
    evidence: ["Owner assignment", "Sponsor assignment", "Access review attestation"],
    frameworks: ["NIST CSF", "ISO 27001", "SOC 2", "COBIT"],
  },
  {
    id: "agent-passport-required",
    name: "Agent Passport Required",
    category: "Baseline",
    pack: "Required Baseline",
    decision: "Challenge",
    enforcementMode: "Challenge",
    riskTier: "High",
    rule: "Require purpose, data scope, tools, credentials, owners, controls, and evidence before production approval.",
    businessValue: "Turns each agent into an audit-ready identity record.",
    configuration: ["Required passport fields", "Production gate", "Exception expiration"],
    evidence: ["Passport completeness score", "Control list", "Approval trail"],
    frameworks: ["NIST AI RMF", "ISO 27001", "SOC 2", "COBIT"],
  },
  {
    id: "least-privilege-required",
    name: "Least Privilege Required",
    category: "Baseline",
    pack: "Required Baseline",
    decision: "Challenge",
    enforcementMode: "Challenge",
    riskTier: "Critical",
    rule: "Agents must only hold permissions required for their approved purpose and operating environment.",
    businessValue: "Reduces attack surface and privilege creep for non-human identities.",
    configuration: ["Allowed tools", "Allowed scopes", "Privileged permission list"],
    evidence: ["Permission diff", "Access review", "Remediation owner"],
    frameworks: ["NIST CSF", "ISO 27001", "SOC 2", "CIS"],
  },
  {
    id: "time-bound-credential-required",
    name: "Time-Bound Credential Required",
    category: "Baseline",
    pack: "Required Baseline",
    decision: "Challenge",
    enforcementMode: "Challenge",
    riskTier: "High",
    rule: "Prefer short-lived, rotated, or just-in-time credentials over standing privileged secrets.",
    businessValue: "Limits damage if an agent token or machine credential is exposed.",
    configuration: ["Maximum credential age", "Rotation owner", "JIT duration"],
    evidence: ["Credential age", "Rotation event", "JIT approval"],
    frameworks: ["NIST CSF", "ISO 27001", "SOC 2", "CIS"],
  },
  {
    id: "audit-evidence-required",
    name: "Audit Evidence Required",
    category: "Baseline",
    pack: "Required Baseline",
    decision: "Monitor",
    enforcementMode: "Monitor",
    riskTier: "Medium",
    rule: "Every material agent action must record actor, action, target, data context, policy decision, and result.",
    businessValue: "Makes investigations and compliance exports defensible.",
    configuration: ["Evidence retention period", "Required event fields", "Export framework"],
    evidence: ["Decision trace", "Audit event", "Evidence package"],
    frameworks: ["NIST CSF", "ISO 27001", "SOC 2", "GDPR", "COBIT"],
  },
];

export const signaturePolicies: PolicyTemplate[] = [
  {
    id: "purpose-bound-access",
    name: "Purpose-Bound Access",
    category: "AgentShield Signature",
    pack: "Runtime Governance",
    decision: "Challenge",
    enforcementMode: "Challenge",
    riskTier: "Critical",
    rule: "Allow an agent to access only the data, tools, and systems that match its registered business purpose.",
    businessValue: "Moves beyond static permissions into business-context authorization.",
    configuration: ["Approved purpose", "Allowed data classes", "Allowed tools"],
    evidence: ["Purpose match", "Data classification", "Decision trace"],
    frameworks: ["NIST AI RMF", "NIST CSF", "ISO 27001", "SOC 2"],
  },
  {
    id: "intent-mismatch-detection",
    name: "Intent Mismatch Detection",
    category: "AgentShield Signature",
    pack: "Runtime Governance",
    decision: "Challenge",
    enforcementMode: "Challenge",
    riskTier: "Critical",
    rule: "Challenge actions where the current task intent conflicts with the agent passport, owner approval, or expected workflow.",
    businessValue: "Catches risky agent behavior that traditional IAM would technically allow.",
    configuration: ["Task context", "Approved workflow", "Challenge threshold"],
    evidence: ["Intent signal", "Matched passport purpose", "Reviewer decision"],
    frameworks: ["NIST AI RMF", "ISO 27001", "SOC 2"],
  },
  {
    id: "autonomy-level-enforcement",
    name: "Autonomy Level Enforcement",
    category: "AgentShield Signature",
    pack: "Autonomy Control",
    decision: "Challenge",
    enforcementMode: "Challenge",
    riskTier: "High",
    rule: "Control whether an agent can act as assistive, supervised, semi-autonomous, or fully autonomous.",
    businessValue: "Gives customers a simple control language for agent independence.",
    configuration: ["Autonomy level", "Allowed action count", "Approval rules"],
    evidence: ["Autonomy setting", "Action count", "Approval record"],
    frameworks: ["NIST AI RMF", "COBIT", "ISO 27001"],
  },
  {
    id: "delegated-user-risk-inheritance",
    name: "Delegated User Risk Inheritance",
    category: "AgentShield Signature",
    pack: "Identity Context",
    decision: "Challenge",
    enforcementMode: "Challenge",
    riskTier: "High",
    rule: "When an agent acts for a user, inherit user risk, session risk, and entitlement risk before allowing the action.",
    businessValue: "Prevents risky users from amplifying access through agents.",
    configuration: ["User risk source", "Session risk threshold", "Inherited permissions"],
    evidence: ["Delegated user", "Risk signal", "Decision trace"],
    frameworks: ["NIST CSF", "ISO 27001", "SOC 2"],
  },
  {
    id: "agent-chain-control",
    name: "Agent-To-Agent Chain Control",
    category: "AgentShield Signature",
    pack: "Autonomy Control",
    decision: "Challenge",
    enforcementMode: "Challenge",
    riskTier: "Critical",
    rule: "Detect and control one agent invoking another agent, workflow, bot, service account, or MCP tool chain.",
    businessValue: "Stops invisible delegated automation chains from bypassing governance.",
    configuration: ["Allowed downstream agents", "Maximum chain depth", "Approval trigger"],
    evidence: ["Invocation graph", "Downstream identity", "Approval decision"],
    frameworks: ["NIST AI RMF", "NIST CSF", "ISO 27001"],
  },
  {
    id: "toxic-permission-combination",
    name: "Toxic Permission Combination Detection",
    category: "AgentShield Signature",
    pack: "Blast Radius",
    decision: "Challenge",
    enforcementMode: "Challenge",
    riskTier: "Critical",
    rule: "Flag combinations such as sensitive data read, export capability, external API access, and privileged write access.",
    businessValue: "Explains why a technically valid permission set creates business risk.",
    configuration: ["Toxic combinations", "Data classes", "Privileged actions"],
    evidence: ["Permission graph", "Combination match", "Remediation plan"],
    frameworks: ["NIST CSF", "ISO 27001", "SOC 2", "CIS"],
  },
  {
    id: "blast-radius-expansion",
    name: "Blast Radius Expansion Detection",
    category: "AgentShield Signature",
    pack: "Blast Radius",
    decision: "Monitor",
    enforcementMode: "Monitor",
    riskTier: "High",
    rule: "Alert when an agent gains access to new apps, repos, datasets, roles, tools, or environments outside its baseline.",
    businessValue: "Shows security teams where agent risk is expanding before an incident.",
    configuration: ["Baseline period", "Expansion threshold", "Notification owner"],
    evidence: ["Access diff", "New resource", "Owner review"],
    frameworks: ["NIST CSF", "ISO 27001", "SOC 2"],
  },
  {
    id: "shadow-agent-quarantine",
    name: "Shadow Agent Quarantine",
    category: "AgentShield Signature",
    pack: "Discovery Response",
    decision: "Quarantine",
    enforcementMode: "Quarantine",
    riskTier: "Critical",
    rule: "Automatically flag or quarantine newly discovered unmanaged agents until ownership, purpose, and access are reviewed.",
    businessValue: "Turns discovery into immediate control, not another dashboard queue.",
    configuration: ["Discovery sources", "Quarantine action", "Exception approver"],
    evidence: ["Discovery event", "Quarantine event", "Approval outcome"],
    frameworks: ["NIST CSF", "ISO 27001", "SOC 2", "CIS"],
  },
  {
    id: "high-impact-action-challenge",
    name: "High-Impact Action Challenge",
    category: "AgentShield Signature",
    pack: "Runtime Governance",
    decision: "Challenge",
    enforcementMode: "Challenge",
    riskTier: "Critical",
    rule: "Require approval for delete, deploy, export, permission change, credential creation, financial action, and customer-impacting action.",
    businessValue: "Keeps agent speed while preserving human accountability at moments that matter.",
    configuration: ["High-impact action list", "Approver group", "Approval timeout"],
    evidence: ["Action request", "Approval decision", "Result"],
    frameworks: ["NIST CSF", "ISO 27001", "SOC 2", "COBIT"],
  },
  {
    id: "data-boundary-enforcement",
    name: "Data Boundary Enforcement",
    category: "AgentShield Signature",
    pack: "Data Protection",
    decision: "Deny",
    enforcementMode: "Block",
    riskTier: "Critical",
    rule: "Prevent agents from crossing customer, tenant, region, department, or environment data boundaries.",
    businessValue: "Protects SaaS providers and regulated customers from cross-boundary exposure.",
    configuration: ["Tenant boundary", "Region boundary", "Environment boundary"],
    evidence: ["Boundary match", "Blocked target", "Decision trace"],
    frameworks: ["GDPR", "NIST CSF", "ISO 27001", "SOC 2"],
  },
  {
    id: "agent-kill-switch",
    name: "Agent Kill Switch",
    category: "AgentShield Signature",
    pack: "Runtime Response",
    decision: "Quarantine",
    enforcementMode: "Quarantine",
    riskTier: "Critical",
    rule: "Allow authorized admins to immediately suspend an agent across connected systems when critical risk is detected.",
    businessValue: "Makes response operational, fast, and provable.",
    configuration: ["Authorized roles", "Connected systems", "Restore approval"],
    evidence: ["Kill switch event", "Systems affected", "Restore decision"],
    frameworks: ["NIST CSF", "ISO 27001", "SOC 2"],
  },
  {
    id: "real-time-decision-trace",
    name: "Real-Time Decision Trace",
    category: "AgentShield Signature",
    pack: "Evidence Intelligence",
    decision: "Monitor",
    enforcementMode: "Monitor",
    riskTier: "High",
    rule: "Record every allow, challenge, deny, quarantine, and approval decision with identity, intent, data, tool, and result context.",
    businessValue: "Creates a defensible audit trail for agentic decisions.",
    configuration: ["Trace fields", "Retention", "Export frameworks"],
    evidence: ["Decision trace", "Policy match", "Evidence export"],
    frameworks: ["NIST AI RMF", "NIST CSF", "ISO 27001", "SOC 2", "COBIT"],
  },
];

export const customPolicyLibrary: PolicyTemplate[] = [
  {
    id: "healthcare-phi-pack",
    name: "Healthcare PHI Protection Pack",
    category: "Custom Library",
    pack: "Healthcare",
    decision: "Challenge",
    enforcementMode: "Challenge",
    riskTier: "Critical",
    rule: "Require approval, audit evidence, and purpose limitation for agents accessing PHI or patient records.",
    businessValue: "Supports HIPAA-focused agent governance for healthcare workflows.",
    configuration: ["PHI data classes", "Clinical workflow", "HIPAA approver"],
    evidence: ["PHI access event", "Approval record", "HIPAA evidence"],
    frameworks: ["HIPAA", "NIST CSF", "ISO 27001"],
  },
  {
    id: "financial-services-pack",
    name: "Financial Services Control Pack",
    category: "Custom Library",
    pack: "Financial Services",
    decision: "Challenge",
    enforcementMode: "Challenge",
    riskTier: "Critical",
    rule: "Protect payment data, trading data, financial records, SOX evidence, and privileged transactions.",
    businessValue: "Gives banks, fintechs, and finance teams a faster starting point.",
    configuration: ["Financial data classes", "Transaction actions", "SOX control owner"],
    evidence: ["Access record", "Transaction approval", "SOX evidence"],
    frameworks: ["SOX", "PCI DSS", "NIST CSF", "SOC 2"],
  },
  {
    id: "devops-agent-pack",
    name: "DevOps Agent Pack",
    category: "Custom Library",
    pack: "Software Engineering",
    decision: "Challenge",
    enforcementMode: "Challenge",
    riskTier: "High",
    rule: "Control GitHub bots, repository writes, CI/CD deployment triggers, source code access, and secrets exposure.",
    businessValue: "Protects modern engineering automation and AI coding workflows.",
    configuration: ["Protected repositories", "Deployment environments", "Secret patterns"],
    evidence: ["Repository permission", "Deployment approval", "Secret scan result"],
    frameworks: ["NIST CSF", "SOC 2", "CIS"],
  },
  {
    id: "cloud-identity-pack",
    name: "Cloud Identity Pack",
    category: "Custom Library",
    pack: "Cloud Security",
    decision: "Monitor",
    enforcementMode: "Monitor",
    riskTier: "High",
    rule: "Review Azure service principals, AWS IAM roles, Kubernetes service accounts, cloud admin permissions, and stale credentials.",
    businessValue: "Unifies cloud non-human identity governance across providers.",
    configuration: ["Cloud provider", "Privileged role list", "Credential age threshold"],
    evidence: ["Cloud role map", "Credential age", "Access review"],
    frameworks: ["NIST CSF", "ISO 27001", "CIS"],
  },
  {
    id: "regional-privacy-pack",
    name: "Regional Privacy Pack",
    category: "Custom Library",
    pack: "Privacy",
    decision: "Deny",
    enforcementMode: "Block",
    riskTier: "Critical",
    rule: "Control GDPR, UK GDPR, CCPA/CPRA, data residency, and cross-border transfer risks for agent actions.",
    businessValue: "Helps multinational customers enforce region-aware data boundaries.",
    configuration: ["Allowed regions", "Data residency rules", "Transfer approval"],
    evidence: ["Region match", "Transfer decision", "Privacy evidence"],
    frameworks: ["GDPR", "UK GDPR", "CCPA/CPRA", "ISO 27001"],
  },
  {
    id: "legal-confidentiality-pack",
    name: "Legal Confidentiality Pack",
    category: "Custom Library",
    pack: "Legal",
    decision: "Challenge",
    enforcementMode: "Challenge",
    riskTier: "Critical",
    rule: "Protect client matters, privileged documents, external AI usage, and attorney review workflows.",
    businessValue: "Fits law firms and legal departments handling privileged material.",
    configuration: ["Matter ID", "Privileged data labels", "Reviewer group"],
    evidence: ["Matter access", "Review decision", "Confidentiality evidence"],
    frameworks: ["ISO 27001", "SOC 2", "GDPR"],
  },
];

export const policyTemplates = [
  ...requiredBaselinePolicies,
  ...signaturePolicies,
  ...customPolicyLibrary,
];

export function buildTenantPolicy(template: PolicyTemplate, tenantId: string, status: TenantPolicy["status"] = "Active"): TenantPolicy {
  const now = new Date().toISOString();

  return {
    ...template,
    id: `${tenantId}-${template.id}`,
    tenantId,
    status,
    source: "standard",
    createdAt: now,
    updatedAt: now,
  };
}

export function getPolicyTemplate(templateId: string) {
  return policyTemplates.find((template) => template.id === templateId) ?? null;
}
